### ISSUE TITLE
Running git submodule update --init

### ISSUE THREAD

**Issue by tomerwolgithub** [ElementAI/duorat#2]
Hi, I've followed the instructions in the README, and I seem to have trouble running `git submodule update --init`. Is it possible that third_party/spider is not public?

Thanks!

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:ElementAI/spider.git' into submodule path '/media/disk1/tomerwolfson/duorat/third_party/spider' failed
Failed to clone 'third_party/spider'. Retry scheduled
Cloning into '/media/disk1/tomerwolfson/duorat/third_party/spider'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:ElementAI/spider.git' into submodule path '/media/disk1/tomerwolfson/duorat/third_party/spider' failed
Failed to clone 'third_party/spider' a second time, aborting
```

**Comment by tscholak** [comment]
Hi @tomerwolgithub, thanks for checking out our code!
The problem you describe is related to the way we have added the `spider` git submodule. we are using the ssh link `git@github.com:ElementAI/spider.git`, and it seems you do not have an ssh key configured with GitHub.
The easiest fix would be if you followed this guide to configure your git client for ssh public key authentication:
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh.

**Comment by tomerwolgithub** [comment]
Great, thanks for the swift response!
